### PR TITLE
Add support for string items in Menu.

### PR DESCRIPTION
**Pull request by derekisbusy**

### CODE REVIEW

**Comment by githubjeka** [comment]
Please provide any examples with string value

**Comment by schmunk42** [comment]
Maybe `---`? Isn't that treated as a separator by Yii2?

**Comment by githubjeka** [comment]
Any case Menu has [linkTemplate](http://www.yiiframework.com/doc-2.0/yii-widgets-menu.html#$linkTemplate-detail) and string value for $item is strange

**Comment by derekisbusy** [comment]
Yes, in the original menu I had it used strings like `<li class="separator"></li>` to add separators. Template makes more sense.

**Pull request closed without merging**
