### PR TITLE
Issue #103 Improve plugin asset example

### PR DESCRIPTION
**Pull request by mikehaertl**
Improves example in #103.

### CODE REVIEW

**Comment by githubjeka** [comment]
Do you know when you set `'@vendor/almasaeed2010/adminlte/plugins';` *all* plugins will be published in assets dirrectory ?

**Comment by githubjeka** [comment]
That why your example not is improve.

**Comment by mikehaertl** [comment]
> Do you know when you set '@vendor/almasaeed2010/adminlte/plugins'; all plugins will be published in assets dirrectory ?

I can not see, why this is a problem. Maybe you want *all* plugins.

**Comment by githubjeka** [comment]
I want add one datepicker plugin,but by your example I get application which will be increase to ~12Mb. In `exsample.com/asssets/hashcode/....` I can see all files of other plugins.

**Comment by githubjeka** [comment]
May be need to add note about it. And return initial example as alternative variant to fix problem/

**Comment by mikehaertl** [comment]
> I want add one datepicker plugin,but by your example I get application which will be increase to ~12Mb.

That's not true. The client will only load the assets that you list in `css` and `js`.

**Comment by githubjeka** [comment]
image
image

**Comment by mikehaertl** [comment]
Not sure what you try to say here. You're on the *server*. The size of the assets directory on the server does not matter. All that matters is the size of the scripts that the client actually loads.

**Comment by githubjeka** [comment]
>  All that matters is the size of the scripts that the client actually loads.

You are right. 
About size and access to files of the assets directory - I don't agree that it should be neglected.

Need opinion of a third party. @schmunk42

**Comment by mikehaertl** [comment]
I think you're now making up a problem where there is none. The size of the assets folder *is* neglectible. You already have all this stuff in the vendor folder and didn't care about the size there either.

**Comment by githubjeka** [comment]
@mikehaertl I not making this up. This case discused several times as I remember. People are concerned about it.

https://github.com/dmstr/yii2-adminlte-asset/pull/46#issuecomment-103053408
[Hack in other pack](https://github.com/rmrevin/yii2-fontawesome/blob/2.9.0/AssetBundle.php#L32-L39)

**Comment by mikehaertl** [comment]
IMO these are all just discussions about none-problems: Someone sees the size of the asset folder on the server and is concerned that something is wrong. But it isn't. So unless we find a real issue with exact definition of *why* this is a problem - there is no problem.

**Comment by schmunk42** [comment]
You're both right :D

There are edge cases (I think it was more related to local development) when (re-)publishing a lot of files simply takes some time. I looked a the plugins directory and it's ~13 MB, so not that small. 

But on the other hand we're on the server and it should also not really matter because the files are usually just copied one single time or are bundled anyway.

Long story short, I'd actually like to have both examples in the docs, so people can choose for theirself. WDYT?

**Comment by githubjeka** [comment]
https://github.com/dmstr/yii2-adminlte-asset/pull/104#issuecomment-265965716

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
